# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/lcd_init_data/lcd_init_data.xci
# IP: The module: 'lcd_init_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/lcd_init_data/lcd_init_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_init_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/lcd_init_data/lcd_init_data.xci
# IP: The module: 'lcd_init_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/lcd_init_data/lcd_init_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_init_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
