# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/axi_crossbar.xci
# IP: The module: 'axi_crossbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/axi_crossbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/axi_crossbar.xci
# IP: The module: 'axi_crossbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/axi_crossbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
