# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xci
# IP: The module: 'clk_pll_33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xci
# IP: The module: 'clk_pll_33' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_pll_33'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
