# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32.xci
# IP: The module: 'dpram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_512x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32.xci
# IP: The module: 'dpram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/net/nscscc2019ucas-master/display/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_512x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
