# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/init/lcd_init_data.coe
add_files d:/net/npu.coe
add_files e:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/init/init_image.coe
add_files d:/net/npu1.coe
read_verilog {
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/global_defines.vh
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/AXICache_defines.vh
  E:/study/game/code/test/display/soc_up/rtl/TOP/config.h
  E:/study/game/code/test/display/soc_up/rtl/MAC/utility.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_defines.h
}
set_property file_type "Verilog Header" [get_files E:/study/game/code/test/display/soc_up/rtl/TOP/config.h]
set_property file_type "Verilog Header" [get_files E:/study/game/code/test/display/soc_up/rtl/MAC/utility.v]
set_property file_type "Verilog Header" [get_files E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_defines.h]
read_verilog -library xil_defaultlib -sv E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/xpm_memory_spram.sv
read_verilog -library xil_defaultlib {
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/AXI_Interface.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/BPU.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/CP0_Reg.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/DCache.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/DTLB_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/EXE_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/FIFO.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/ICache.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/ID_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/IF_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/ITLB_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/M1_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/MEM_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/PLRU.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/PREIF_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/WB_stage.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/XPMRAMS.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/alu.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/apb_dev_top.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/apb_mux2.v
  E:/study/game/code/test/display/soc_up/rtl/AMBA/axi2apb.v
  E:/study/game/code/test/display/soc_up/rtl/AMBA/axi_mux.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/bd.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/cloclz_cnt.v
  E:/study/game/code/test/display/soc_up/rtl/CONFREG/confreg.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/csr.v
  E:/study/game/code/test/display/soc_up/rtl/DMA/dma.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/dma.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/ethernet_top.v
  E:/study/game/code/test/display/soc_up/rtl/SPI/godson_sbridge_spi.v
  E:/study/game/code/test/display/soc_up/rtl/CONFREG/lcd.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/mac.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/mac2axi.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/mac_axi.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/mac_top.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/maccsr2axi.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/macdata2axi.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/mycpu_top.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/NAND/nand.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/nand_module.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/raminfr.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/rc.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/regfile.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/rfifo.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/rlsm.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/rstc.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/tc.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/tfifo.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/tlb.v
  E:/study/game/code/test/display/soc_up/rtl/MAC/tlsm.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/tools.v
  E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/trap.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_receiver.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_regs.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_rfifo.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_sync_flops.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_tfifo.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_top.v
  E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_transmitter.v
  E:/study/game/code/test/display/soc_up/rtl/TOP/soc_up_top.v
}
read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/mig_axi_32/mig_axi_32/user_design/constraints/mig_axi_32_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0.xci
set_property used_in_synthesis false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/axi_interconnect_0/axi_interconnect_0_clocks.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_board.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_late.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33/clk_pll_33_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/dpram_512x32/dpram_512x32_ooc.xdc]

read_ip -quiet E:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/axi_crossbar.xci
set_property used_in_implementation false [get_files -all e:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/axi_crossbar_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/multiplier/multiplier.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/multiplier/multiplier_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv/mydiv.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv/mydiv_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv_unsigned/mydiv_unsigned.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv_unsigned/mydiv_unsigned_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/ex_ila.xci
set_property used_in_synthesis false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/ex_ila_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/pc_ila.xci
set_property used_in_synthesis false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/pc_ila_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/complex_ila.xci
set_property used_in_synthesis false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/complex_ila_ooc.xdc]

read_ip -quiet E:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/init_img_rom/init_img_rom.xci
set_property used_in_implementation false [get_files -all e:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/init_img_rom/init_img_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/study/game/code/test/display/soc_up/vivado_xpr/soc_up.xdc
set_property used_in_implementation false [get_files E:/study/game/code/test/display/soc_up/vivado_xpr/soc_up.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_up_top -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_up_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_up_top_utilization_synth.rpt -pb soc_up_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
