# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv_unsigned/mydiv_unsigned.xci
# IP: The module: 'mydiv_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv_unsigned/mydiv_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mydiv_unsigned'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv_unsigned/mydiv_unsigned.xci
# IP: The module: 'mydiv_unsigned' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/mydiv_unsigned/mydiv_unsigned_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mydiv_unsigned'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
