# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a200tfbg676-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core
    E:/study/game/code/test/display/soc_up/rtl/TOP
    E:/study/game/code/test/display/soc_up/rtl/MAC
    E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33
    e:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/hdl
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/hdl/verilog
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/hdl/verilog
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/hdl/verilog
    e:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/init_img_rom
  } {
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/xpm_memory_spram.sv
      D:/vivado/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/vivado/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core
    E:/study/game/code/test/display/soc_up/rtl/TOP
    E:/study/game/code/test/display/soc_up/rtl/MAC
    E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_wiz_0
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/xilinx_ip/clk_pll_33
    e:/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/axi_crossbar/hdl
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/ex_ila/hdl/verilog
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/pc_ila/hdl/verilog
    e:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.srcs/sources_1/ip/complex_ila/hdl/verilog
    e:/study/game/code/test/display/soc_up/rtl/CONFREG/LCD/ip/init_img_rom
  } {
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/mig_axi_32_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/axi_interconnect_0_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/clk_wiz_0_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/clk_pll_33_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/dpram_512x32_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/axi_crossbar_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/multiplier_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/mydiv_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/mydiv_unsigned_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/ex_ila_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/pc_ila_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/complex_ila_stub.v
      E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/init_img_rom_stub.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/AXI_Interface.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/BPU.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/CP0_Reg.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/DCache.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/DTLB_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/EXE_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/FIFO.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/ICache.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/ID_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/IF_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/ITLB_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/M1_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/MEM_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/PLRU.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/PREIF_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/WB_stage.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/XPMRAMS.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/alu.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/apb_dev_top.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/apb_mux2.v
      E:/study/game/code/test/display/soc_up/rtl/AMBA/axi2apb.v
      E:/study/game/code/test/display/soc_up/rtl/AMBA/axi_mux.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/bd.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/cloclz_cnt.v
      E:/study/game/code/test/display/soc_up/rtl/CONFREG/confreg.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/csr.v
      E:/study/game/code/test/display/soc_up/rtl/DMA/dma.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/dma.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/ethernet_top.v
      E:/study/game/code/test/display/soc_up/rtl/SPI/godson_sbridge_spi.v
      E:/study/game/code/test/display/soc_up/rtl/CONFREG/lcd.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/mac.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/mac2axi.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/mac_axi.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/mac_top.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/maccsr2axi.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/macdata2axi.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/mycpu_top.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/NAND/nand.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/nand_module.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/raminfr.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/rc.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/regfile.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/rfifo.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/rlsm.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/rstc.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/tc.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/tfifo.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/tlb.v
      E:/study/game/code/test/display/soc_up/rtl/MAC/tlsm.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/tools.v
      E:/study/game/code/test/display/soc_up/rtl/MIRROR_SWAMP/core/trap.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_receiver.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_regs.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_rfifo.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_sync_flops.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_tfifo.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_top.v
      E:/study/game/code/test/display/soc_up/rtl/APB_DEV/URT/uart_transmitter.v
      E:/study/game/code/test/display/soc_up/rtl/TOP/soc_up_top.v
    }
      rt::read_vhdl -lib xpm D:/vivado/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/realtime/soc_up_top_synth.xdc
    rt::sdcChecksum
    set rt::top soc_up_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.cache/wt}
    rt::set_parameter enableSplitFlowPath "E:/study/game/code/test/display/soc_up/vivado_xpr/project_1/project_1/project_1.runs/synth_1/.Xil/Vivado-5232-LAPTOP-S513OG68/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
